spring.application.name=products-api
server.port=8080

spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.content-type=application/json

spring.cloud.function.definition=handleReplies
spring.cloud.stream.bindings.handleReplies-in-0.destination=products.replies
spring.cloud.stream.bindings.handleReplies-in-0.content-type=application/json
spring.cloud.stream.bindings.handleReplies-in-0.group=products.api
spring.cloud.stream.kafka.bindings.handleReplies-in-0.consumer.startOffset=latest

spring.cloud.stream.kafka.binder.brokers=localhost:9092
