spring.application.name=products-api
server.port=8080

spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.content-type=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092
