@baseUrl = http://localhost:8080
@contentType = application/json

### GET request with a header
GET {{baseUrl}}/ping
Accept: {{contentType}}

### POST request
POST {{baseUrl}}/products
Content-Type: {{contentType}}

{
  "name": "Monitor",
  "price": 3000.00
}

### POST request
POST {{baseUrl}}/products
Content-Type: {{contentType}}

{
  "name": "Mouse RGB MySQL",
  "price": 11.50
}

### POST request
POST {{baseUrl}}/products
Content-Type: {{contentType}}

{
  "name": "lampara de escritorio",
  "price": 2100.50
}

### POST request
POST {{baseUrl}}/products
Content-Type: {{contentType}}

{
  "name": "Microfono para grabar",
  "price": 12.99
}
